# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'avtoriz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(445, 728)
        Form.setStyleSheet("QLineEdit \n"
"{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:#717072;\n"
"    border-bottom:1px solid #717072;\n"
"}\n"
"*{\n"
"    font-family:century gothic;\n"
"    font-size:24px;\n"
"}\n"
"QFrame {\n"
"    background:#333;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover \n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#49ebff;\n"
"}\n"
"QToolButton \n"
"{\n"
"    background:red;\n"
"    border-radius:50px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"}\n"
"")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 660, 241, 41))
        self.pushButton.setStyleSheet("\n"
"QPushButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:60px;\n"
"}\n"
"QToolButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:50px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover \n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#49ebff;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 600, 241, 41))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:60px;\n"
"}\n"
"QToolButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:50px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover \n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#49ebff;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(240, 240, 91, 31))
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 320, 101, 31))
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(-70, -120, 941, 891))
        self.tableWidget.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(210, 228, 255);\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 540, 241, 41))
        self.pushButton_3.setStyleSheet("\n"
"QPushButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:60px;\n"
"}\n"
"QToolButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:50px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover \n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#49ebff;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "entrance"))
        self.pushButton_2.setText(_translate("Form", "registration"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Логин"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Пароль"))
        self.pushButton_3.setText(_translate("Form", "Admin Panel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
