# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(710, 487)
        Form.setStyleSheet("QTableWidget \n"
"{\n"
"    color:white;\n"
"    background-color:#333;\n"
"    selection-color:green;\n"
"    font: 700 8pt \"Arial\";\n"
"    selection-background-color:#FF0000;\n"
"    gridline-color:#DC143C\n"
"}\n"
"\n"
"QTableWidget::item:selected\n"
"{\n"
"    color:white;\n"
"    background-color:#A52A2A;\n"
"}\n"
"\n"
"QHeaderView \n"
"{\n"
"    border:none;\n"
"    font: 700 8pt \"Arial\";\n"
"    background-color:#333;\n"
"    color:white;\n"
"    border:2px solid #696969;\n"
"}\n"
"\n"
"QHeaderView::section \n"
"{\n"
"    border:none;\n"
"    font: 700 8pt \"Arial\";\n"
"    background-color:#333;\n"
"    color:white;\n"
"}\n"
"*{\n"
"    font-family:century gothic;\n"
"    font-size:24px;\n"
"}\n"
"\n"
"QFrame {\n"
"    background:#333;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    background:red;\n"
"    border-radius:60px;\n"
"}\n"
"QToolButton \n"
"{\n"
"    background:red;\n"
"    border-radius:50px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover \n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#49ebff;\n"
"}\n"
"\n"
"QLineEdit \n"
"{\n"
"    background:transparent;\n"
"    border:none;\n"
"    color:#717072;\n"
"    border-bottom:1px solid #717072;\n"
"    background-color: rgb(205, 255, 247);\n"
"}\n"
"QWidget\n"
"{\n"
"    background-color: rgb(210, 228, 255);\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 370, 141, 41))
        self.pushButton.setStyleSheet("\n"
"QPushButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:60px;\n"
"}\n"
"QToolButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:50px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover \n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#49ebff;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 370, 121, 41))
        self.pushButton_2.setStyleSheet("\n"
"QPushButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:60px;\n"
"}\n"
"QToolButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:50px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover \n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#49ebff;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 370, 121, 41))
        self.pushButton_3.setStyleSheet("\n"
"QPushButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:60px;\n"
"}\n"
"QToolButton \n"
"{\n"
"    background:#868eff;\n"
"    border-radius:50px;\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    color:white;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover \n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#49ebff;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(160, 130, 401, 201))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(330, 40, 81, 21))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "add"))
        self.pushButton_2.setText(_translate("Form", "delete"))
        self.pushButton_3.setText(_translate("Form", "update"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Фамилия"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Логин"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Пароль"))
        self.label.setText(_translate("Form", "users"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
